CREATE DATABASE Grading
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER 'grader'@'localhost' IDENTIFIED BY 'grades';

GRANT ALTER, CREATE, DELETE, DROP, INDEX, INSERT, SELECT, UPDATE
  ON Grading.*
  TO 'grader'@'localhost';

CREATE TABLE Grading.Users(
  NetID Char(8) NOT NULL,
  LastName Varchar(32) NOT NULL,
  FirstName Varchar(64) NOT NULL,
  pwHash Char(64),
  pwSalt Char(64),
  PRIMARY KEY(NetID),
  INDEX (LastName)
) ENGINE=InnoDB;

CREATE TABLE Grading.Courses(
  ID Char(38), # generated by "C_" + uuid.uuid4()
  CourseNumber Char(7) UNIQUE,
  PRIMARY KEY(ID),
  INDEX(CourseNumber)
) ENGINE=InnoDB;

CREATE TABLE Grading.Semesters(
  ID Char(38), # generated by "S_" + uuid.uuid4()
  Name Char(4),
  Class Char(38),
  PRIMARY KEY(ID, Class),
  INDEX(Class),
  INDEX(Name),
  FOREIGN KEY (Class)
    REFERENCES Grading.Courses(ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;

# Each semester table will be of the form:
#
# CREATE TABLE S_*****(
#   NetID Char(8) REFERENCES Users(NetID),
#   Proj1 Int,
#   Proj2 Int,
#   ...
#   Total Numeric(7,2)
# ) ENGINE=InnoDB;
#

CREATE TABLE Grading.Roles(
  NetID Char(8) REFERENCES Users(NetID),
  UserType Enum("ADMIN", "PROF", "TA", "STUDENT") NOT NULL,
  Semester Char(38) NOT NULL,
  Section Char(4),
  PRIMARY KEY(NetID, Semester),
  FOREIGN KEY (Semester)
    REFERENCES Grading.Semesters(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Grading.Assignments(
  ID Char(38) PRIMARY KEY, # generated by "A_" + uuid.uuid4()
  Semester Char(38) NOT NULL,
  Name Varchar(100) NOT NULL,
  Parts Int NOT NULL,
  Points INT NOT NULL,
  INDEX(Semester),
  FOREIGN KEY (Semester)
    REFERENCES Grading.Semesters(ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;

# Each assignment table will be of the form
#
# CREATE TABLE A_*****(
#   NetID Char(8),
#   Part1 Numeric(2,2),
#   Part2 Numeric(2,2),
#   Part3 Numeric(2,2),
#   ...
#   Comments Text,
#   FOREIGN KEY (NetID)
#     REFERENCES Grading.Users(NetID)
#     ON UPDATE CASCADE
#     ON DELETE RESTRICT
# ) ENGINE=InnoDB;
#